-- Pega todo en Supabase > SQL Editor > Run (una sola vez)
create table if not exists sesiones(usuario text primary key, nombre text, rol text, visto bigint, inicio bigint);
create table if not exists turnos(id bigint generated by default as identity primary key, usuario text, nombre text, rol text, inicio bigint);
alter table sesiones enable row level security;
alter table turnos enable row level security;

create or replace function mi_usuario() returns text language sql security definer set search_path=public stable as
$$ select usuario from perfiles where id=auth.uid() $$;

create policy "leer sesiones" on sesiones for select to authenticated using (true);
create policy "crear mi sesion" on sesiones for insert to authenticated with check (usuario = mi_usuario());
create policy "actualizar mi sesion" on sesiones for update to authenticated using (usuario = mi_usuario()) with check (usuario = mi_usuario());
create policy "crear mi turno" on turnos for insert to authenticated with check (usuario = mi_usuario());
create policy "admin lee turnos" on turnos for select to authenticated using (mi_rol() = 'admin');
create policy "admin lee perfiles" on perfiles for select to authenticated using (mi_rol() = 'admin');
